// Code generated by hertz generator.

package main

import (
	handler "dqq/go/math/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.POST("/upload", handler.UploadFile)
	r.POST("/upload_files", handler.UploadMultiFile)

	r.GET("/user/text", handler.Text)
	r.GET("/user/json", handler.Json)
	r.GET("/user/xml", handler.Xml)
	r.GET("/user/pb", handler.ProtoBuf)
	r.GET("/user/cookie", handler.Header)
	r.GET("/user/html", handler.Html)
	r.GET("/user/old_page", handler.Redirect)
	r.GET("/file/:file", handler.File)
}
