// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"log"
	"my_goframe/internal/dao/internal"
	"my_goframe/internal/model/do"

	"github.com/gogf/gf/v2/container/gvar"
)

// internalLoginDao is an internal type for wrapping the internal DAO implementation.
type internalLoginDao = *internal.LoginDao

// loginDao is the data access object for the table login.
// You can define custom methods on it to extend its functionality as needed.
type loginDao struct {
	internalLoginDao
}

var (
	// Login is a globally accessible object for table login operations.
	Login = loginDao{
		internal.NewLoginDao(),
	}
)

// Add your custom methods and functionality below.

func CheckLogin(name, pass string) bool {
	ctx := context.Background()
	var account do.Login
	err := Login.Ctx(ctx).Where("username=?", name).Scan(&account)
	if err != nil {
		log.Println(err)
		return false
	}
	if len(pass) > 0 && pass == account.Password.(*gvar.Var).String() {
		return true
	}
	return false
}
