// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"my_goframe/internal/dao/internal"
)

// internalStudentDao is an internal type for wrapping the internal DAO implementation.
type internalStudentDao = *internal.StudentDao

// studentDao is the data access object for the table student.
// You can define custom methods on it to extend its functionality as needed.
type studentDao struct {
	internalStudentDao
}

var (
	// Student is a globally accessible object for table student operations.
	Student = studentDao{
		internal.NewStudentDao(),
	}
)

// Add your custom methods and functionality below.
