// Code generated by hertz generator.

package math_service

import (
	"context"
	math_service "dqq/go/math/biz/model/math_service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Add .
// @router /add [GET]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math_service.AddRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(math_service.AddResponse)
	resp.Sum = req.Left + req.Right

	c.JSON(consts.StatusOK, resp)
}

// Sub .
// @router /sub [POST]
func Sub(ctx context.Context, c *app.RequestContext) {
	var err error
	var req math_service.SubRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(math_service.SubResponse)
	resp.Diff = req.Left - req.Right

	c.JSON(consts.StatusOK, resp)
}
