// Code generated by hertz generator.

package student_service

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postjsonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _restfulMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cookieMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _headerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postpbMw() []app.HandlerFunc {
	// your code...
	return nil
}
